# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CKYS' do
  
pod 'Masonry', '~> 0.6.4'

pod 'UIButtonUnit'

pod 'SDCycleScrollView','~> 1.75'

pod 'AFNetworking', '~> 3.1.0'

pod 'MJRefresh', '~> 3.1.15.3’

pod 'MJExtension', '~> 3.0.13'

pod 'YYModel'

pod 'SDWebImage'


end
